---

- name: Trust the docker apt key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: Add the docker apt repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present update_cache=yes

- name: Install docker
  apt: pkg=lxc-docker state=present

- name: Enable docker service
  service: name=docker state=started enabled=yes
